### ISSUE TITLE
Endpoints faltantes com opções do formulário de perfil

### ISSUE THREAD

**Issue by vstgio** [wikimediabrasil/capx-backend#16]
- territory
- language
- wikimedia_project
- skills_known
- skills_available
- skills_wanted

**Comment by albertoleoncio** [comment]
@vstgio Algumas notas:

- `/affiliations` foi renomeado para `/list_organizations`, para padronizar os endpoints de somente leitura
- A lista de endpoints está em [CapX/urls.py#L42-L47](https://github.com/WikiMovimentoBrasil/capx-backend/blob/35debae487ddb1b0e7ab255499022d64da5e9d2e/CapX/urls.py#L42-L47)
- A lista de skills retornará apenas os Qid dos itens do Wikidata. Para consultar os labels correspondentes, é necessário uma outra query diretamente no Wikidata usando SPARQL.
  - Essa é uma query de exemplo: https://w.wiki/AJjs
  - Essa é a mesma consulta via API endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql?format=json&query=SELECT%20?item%20?itemLabel%20WHERE{VALUES%20?item%20{wd:Q1%20wd:Q2%20wd:Q3}SERVICE%20wikibase:label{bd:serviceParam%20wikibase:language%20%22pt-br,pt,en%22.}}
- Endpoint para busca de imagens: https://commons.wikimedia.org/w/api.php?action=query&list=search&srnamespace=6&srlimit=10&srsearch=term
- Endpoint para converter nome da imagem para path: https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/image.jpg&width=100&height=50
