### ISSUE TITLE
Alterar campo de consulta de "userId" para "username"

### ISSUE THREAD

**Issue by Ederporto** [wikimediabrasil/capx-backend#22]
Para visualizar o perfil de um usuário, pega-se VALOR da URL "/profile/VALOR". Esse valor não tem validação no frontend, mas só retorna algum dado do backend se for o "id" do usuário na base de dados.

A ideia é usar o username do usuário como parser de consulta em https://capx-backend.toolforge.org/users/VALOR

**Comment by albertoleoncio** [comment]
@Ederporto A busca ficou assim: https://capx-backend.toolforge.org/users/?username=VALOR
Quando o usuário não for encontrado, retornará uma array vazia: `[]`
Quando encontrado, retornará o item correspondente ao usuário como elemento único da array de resultados
